# Generated by Django 5.0.3 on 2026-03-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoramentoFrota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_onibus', models.PositiveIntegerField(default=0)),
                ('eletricos', models.PositiveIntegerField(default=0)),
                ('diesel', models.PositiveIntegerField(default=0)),
                ('co2_economizado', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Monitoramento de Frota',
                'verbose_name_plural': 'Monitoramentos de Frota',
            },
        ),
    ]
