# Generated by Django 5.0.3 on 2026-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramentofrota',
            options={'verbose_name': 'Monitoramento da Frota', 'verbose_name_plural': 'Monitoramento da Frota'},
        ),
        migrations.RemoveField(
            model_name='monitoramentofrota',
            name='co2_economizado',
        ),
        migrations.AddField(
            model_name='monitoramentofrota',
            name='co2_evitado',
            field=models.FloatField(default=0.0, verbose_name='CO2 Evitado (Toneladas)'),
        ),
        migrations.AddField(
            model_name='monitoramentofrota',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monitoramentofrota',
            name='diesel',
            field=models.IntegerField(default=13500, verbose_name='Ônibus a Diesel'),
        ),
        migrations.AlterField(
            model_name='monitoramentofrota',
            name='eletricos',
            field=models.IntegerField(default=0, verbose_name='Ônibus Elétricos'),
        ),
        migrations.AlterField(
            model_name='monitoramentofrota',
            name='total_onibus',
            field=models.IntegerField(default=13500, verbose_name='Total da Frota'),
        ),
    ]
