# Generated by Django 5.0.3 on 2026-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_alter_monitoramentofrota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramentofrota',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='Ônibus a Diesel'),
        ),
        migrations.AlterField(
            model_name='monitoramentofrota',
            name='total_onibus',
            field=models.IntegerField(default=0, verbose_name='Total da Frota'),
        ),
    ]
