# Generated by Django 5.0.3 on 2026-03-13 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cor_hex', models.CharField(max_length=7)),
                ('slug_icone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetaReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('progresso', models.FloatField(default=0.0)),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='metas.eixo')),
            ],
        ),
    ]
